name: check
on:
  pull_request:
    paths:
      - 'bun.lockb'
      - 'yarn.lock'
jobs:
  check-diff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: oven-sh/setup-bun@v1
      - uses: ./.github/actions/diff-lock
