name: reserve-sushi-on-1st
on:
  workflow_dispatch:
  schedule:
    - cron: '0 15 28-31 * *'
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Check today is 1st in JST
        run: |
          # Check if it's the first day of the month in JST
          TZ='Asia/Tokyo'
          if [ $(date '+%d') -eq 1 ]; then
            echo "It's the first day of the month in JST"
            echo `date`
          else
            echo "It's not the first day of the month in JST"
            echo `date`
            exit 0
          fi
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup bun
        uses: oven-sh/setup-bun@v1
      - name: Install dependencies
        run: bun install
      - name: Run to reserve sushi
        run: bun run src/index.ts sushi
