name: reserve-sushi-on-1st
on:
  workflow_dispatch:
  schedule:
    - cron: '0 15 12 * *'
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Check today is 1st in JST
        run: |
          # Check if it's the first day of the month in JST
          TZ='Asia/Tokyo'
          if [ $(date '+%d') -eq 1 ]; then
            echo "It's the first day of the month in JST"
            echo `date`
          else
            echo "It's not the first day of the month in JST"
            echo `date`
          fi
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup env
        run: |
          sudo apt-get install -y fonts-noto-cjk
          sudo fc-cache -fv
      - name: Setup bun
        uses: oven-sh/setup-bun@v1
      - name: Install dependencies
        run: bun install
      - name: Run to reserve oukarou
        run: bun run src/index.ts oukarou debug
        env:
          EMAIL: ${{ secrets.EMAIL }}
          CAPTCHA_API_KEY: ${{ secrets.CAPTCHA_API_KEY }}
      - name: Zip ss directory
        run: zip -r ss.zip ss
      - name: Upload ss.zip
        uses: actions/upload-artifact@v4
        with:
          name: ss
          path: ss.zip
