name: reserve-sushi-on-1st
on:
  workflow_dispatch:
  schedule:
    - cron: '0 15 28-31 * *'
jobs:
  run:
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run reservation
        uses: ./.github/actions/run-reservation
        env:
          RESTAURANT: sushi
          EMAIL: ${{ secrets.EMAIL }}
          CAPTCHA_API_KEY: ${{ secrets.CAPTCHA_API_KEY }}
          MODE: ${{ vars.MODE }}
